// JaveScript 关键字
const JS_KEYWORD = [{
    text: '定义抽象类',
    value: 'abstract',
}, {
    text: '参数',
    value: 'arguments',
}, {
    text: '布尔属性',
    value: 'boolean',
}, {
    text: '跳出循环',
    value: 'break',
}, {
    text: '字节',
    value: 'byte',
}, {
    text: 'switch判断语句',
    value: 'switch',
}, {
    text: 'switch分支语句',
    value: 'case',
}, {
    text: '捕获异常，try .. catch',
    value: 'catch',
}, {
    text: '字符',
    value: 'char',
}, {
    text: '定义类',
    value: 'class',
}, {
    text: '定义常量',
    value: 'const',
}, {
    text: '继续执行下一个循环',
    value: 'continue',
}, {
    text: '调试',
    value: 'debugger',
}, {
    text: '默认值、默认属性',
    value: 'default',
}, {
    text: '删除',
    value: 'delete',
}, {
    text: '循环语句',
    value: 'do',
}, {
    text: '双精度类型',
    value: 'double',
}, {
    text: '条件语句',
    value: 'else',
}, {
    text: '枚举类型',
    value: 'enum',
}, {
    text: '执行字符串代码',
    value: 'eval',
}, {
    text: 'ES6 导出模块语法',
    value: 'export',
}, {
    text: '继承',
    value: 'extends',
}, {
    text: '布尔值：非',
    value: 'false',
}, {
    text: '修饰关键词',
    value: 'final',
}, {
    text: '异常处理返回',
    value: 'finally',
}, {
    text: '浮点类型',
    value: 'float',
}, {
    text: '循环语句',
    value: 'for',
}, {
    text: '定义方法',
    value: 'function',
}, {
    text: '跳转逻辑',
    value: 'goto',
}, {
    text: '条件语句',
    value: 'if',
}, {
    text: '实现方法',
    value: 'implements',
}, {
    text: 'ES6 导入模块',
    value: 'import',
}, {
    text: '循环语句 for ... in',
    value: 'in',
}, {
    text: '测试属性是否在对象的prototype中',
    value: 'instanceof',
}, {
    text: '整型',
    value: 'int',
}, {
    text: '接口',
    value: 'interface',
}, {
    text: '定义变量',
    value: 'let',
}, {
    text: '长整型',
    value: 'long',
}, {
    text: '原生属性',
    value: 'native',
}, {
    text: '构造新实例',
    value: 'new',
}, {
    text: '空',
    value: 'null',
}, {
    text: '包',
    value: 'package',
}, {
    text: '私有化',
    value: 'private',
}, {
    text: '受保护',
    value: 'protected',
}, {
    text: '公共',
    value: 'public',
}, {
    text: '返回语句',
    value: 'return',
}, {
    text: '短整型',
    value: 'short',
}, {
    text: '静态',
    value: 'static',
}, {
    text: '可以用来调用父对象上的函数',
    value: 'super',
}, {
    text: '定义单线程方法',
    value: 'synchronized',
}, {
    text: '内部变量',
    value: 'this',
}, {
    text: '抛出函数，抛出异常等',
    value: 'throw',
}, {
    text: '指定抛出多个异常',
    value: 'throws',
}, {
    text: '变量修饰符，避免持久化',
    value: 'transient',
}, {
    text: '布尔值：是',
    value: 'true',
}, {
    text: '异常捕获',
    value: 'try',
}, {
    text: '类型判断',
    value: 'typeof',
}, {
    text: '定义变量，不建议使用',
    value: 'var',
}, {
    text: '无返回值定义',
    value: 'void',
}, {
    text: '变量修饰符，对所有线程可见',
    value: 'volatile',
}, {
    text: '循环语句 do ... while',
    value: 'while',
}, {
    text: '改变作用域',
    value: 'with',
}, {
    text: '使生成器函数执行暂停',
    value: 'yield',
}];

export default JS_KEYWORD;
