// Windows 保留关键字
const WIN_KEYWORD = [{
    text: '弹框',
    value: 'alert',
}, {
    text: '',
    value: 'all',
}, {
    text: '',
    value: 'anchor',
}, {
    text: '',
    value: 'anchors',
}, {
    text: '',
    value: 'area',
}, {
    text: '',
    value: 'assign',
}, {
    text: '失去焦点',
    value: 'blur',
}, {
    text: '按钮',
    value: 'button',
}, {
    text: '多选框',
    value: 'checkbox',
}, {
    text: '清除周期定时器',
    value: 'clearInterval',
}, {
    text: '清除定时器',
    value: 'clearTimeout',
}, {
    text: '浏览器信息',
    value: 'clientInformation',
}, {
    text: '关闭窗口',
    value: 'close',
}, {
    text: '是否关闭',
    value: 'closed',
}, {
    text: '确认弹框',
    value: 'confirm',
}, {
    text: '构造器',
    value: 'constructor',
}, {
    text: '',
    value: 'crypto',
}, {
    text: '解码url',
    value: 'decodeURI',
}, {
    text: '解码url',
    value: 'decodeURIComponent',
}, {
    text: '设置或返回窗口状态栏中的默认文本',
    value: 'defaultStatus',
}, {
    text: 'html文档对象',
    value: 'document',
}, {
    text: '',
    value: 'element',
}, {
    text: '',
    value: 'elements',
}, {
    text: '',
    value: 'embed',
}, {
    text: '',
    value: 'embeds',
}, {
    text: '转码url',
    value: 'encodeURI',
}, {
    text: '转码url',
    value: 'encodeURIComponent',
}, {
    text: '',
    value: 'escape',
}, {
    text: '',
    value: 'event',
}, {
    text: '',
    value: 'fileUpload',
}, {
    text: '获取焦点',
    value: 'focus',
}, {
    text: '',
    value: 'form',
}, {
    text: '',
    value: 'forms',
}, {
    text: '',
    value: 'frame',
}, {
    text: '',
    value: 'innerHeight',
}, {
    text: '',
    value: 'innerWidth',
}, {
    text: '',
    value: 'layer',
}, {
    text: '',
    value: 'layers',
}, {
    text: '',
    value: 'link',
}, {
    text: '',
    value: 'location',
}, {
    text: '',
    value: 'mimeTypes',
}, {
    text: '',
    value: 'navigate',
}, {
    text: '',
    value: 'navigator',
}, {
    text: '',
    value: 'frames',
}, {
    text: '',
    value: 'frameRate',
}, {
    text: '',
    value: 'hidden',
}, {
    text: '',
    value: 'history',
}, {
    text: '',
    value: 'image',
}, {
    text: '',
    value: 'images',
}, {
    text: '',
    value: 'offscreenBuffering',
}, {
    text: '',
    value: 'open',
}, {
    text: '',
    value: 'opener',
}, {
    text: '',
    value: 'option',
}, {
    text: '',
    value: 'outerHeight',
}, {
    text: '',
    value: 'outerWidth',
}, {
    text: '',
    value: 'packages',
}, {
    text: '',
    value: 'pageXOffset',
}, {
    text: '',
    value: 'pageYOffset',
}, {
    text: '',
    value: 'parent',
}, {
    text: '',
    value: 'parseFloat',
}, {
    text: '',
    value: 'parseInt',
}, {
    text: '密码',
    value: 'password',
}, {
    text: '',
    value: 'pkcs11',
}, {
    text: '插件',
    value: 'plugin',
}, {
    text: '',
    value: 'prompt',
}, {
    text: '',
    value: 'propertyIsEnum',
}, {
    text: '单选框',
    value: 'radio',
}, {
    text: '',
    value: 'reset',
}, {
    text: '屏幕',
    value: 'screenX',
}, {
    text: '',
    value: 'screenY',
}, {
    text: '',
    value: 'scroll',
}, {
    text: '',
    value: 'secure',
}, {
    text: '下拉选择',
    value: 'select',
}, {
    text: '',
    value: 'self',
}, {
    text: '设置周期定时器',
    value: 'setInterval',
}, {
    text: '设置定时器',
    value: 'setTimeout',
}, {
    text: '',
    value: 'status',
}, {
    text: 'form提交时间',
    value: 'submit',
}, {
    text: '',
    value: 'taint',
}, {
    text: '文本',
    value: 'text',
}, {
    text: '文本域',
    value: 'textarea',
}, {
    text: '',
    value: 'top',
}, {
    text: '',
    value: 'unescape',
}, {
    text: '',
    value: 'untaint',
}, {
    text: 'window对象',
    value: 'window',
}];

export default WIN_KEYWORD;
